#!/usr/bin/env python3
"""Vendor markstream-vue and its dependencies into assets/vendor/.

The script:
1. Downloads pinned files from jsDelivr (or reads them from --from DIR).
2. Walks the markstream-vue module graph from dist/index.js.
3. Rewrites bare imports to relative paths. Then no import map is needed.
4. Writes assets/manifest.json with upstream and served SHA-384 pins.
5. Writes src/vendored.rs (generated: bundle entries, eager modules).

Run from the crate root: python3 scripts/vendor.py [--from DIR]
"""

import argparse
import base64
import hashlib
import json
import os
import posixpath
import re
import sys
import urllib.request

CDN = "https://cdn.jsdelivr.net/npm"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ASSETS = os.path.join(ROOT, "assets")
VENDOR = "vendor"

# name -> (npm package, version, upstream path, served path under vendor/)
SINGLES = {
    "vue": ("vue", "3.5.43", "dist/vue.runtime.esm-browser.prod.js",
            "vue/vue.runtime.esm-browser.prod.js"),
    "stream-markdown-parser": ("stream-markdown-parser", "1.2.18",
                               "dist/index.js",
                               "stream-markdown-parser/index.js"),
    "markstream-core": ("markstream-core", "2.0.16", "dist/index.js",
                        "markstream-core/index.js"),
    "@floating-ui/dom": ("@floating-ui/dom", "1.8.0",
                         "dist/floating-ui.dom.browser.min.mjs",
                         "floating-ui/dom.js"),
    "@floating-ui/core": ("@floating-ui/core", "1.8.0",
                          "dist/floating-ui.core.browser.min.mjs",
                          "floating-ui/core.js"),
}
MARKSTREAM = ("markstream-vue", "2.0.16")
MARKSTREAM_DIR = "markstream-vue"
MARKSTREAM_CSS = ("dist/index.css", "markstream-vue/index.css")

# Optional peers stay bare. markstream catches the failed import.
OPTIONAL_PEERS = {
    "katex", "katex/dist/contrib/mhchem", "mermaid",
    "stream-diffs/markstream", "@terrastruct/d2",
}

SPEC = re.compile(r"""((?:\bfrom|\bimport)\s*\(?\s*)(["'])([^"'\s]+)\2""")


def sri(data):
    digest = hashlib.sha384(data).digest()
    return "sha384-" + base64.b64encode(digest).decode()


def fetch(pkg, version, path, local):
    if local:
        with open(os.path.join(local, pkg, version, path), "rb") as f:
            return f.read()
    url = f"{CDN}/{pkg}@{version}/{path}"
    with urllib.request.urlopen(url, timeout=60) as resp:
        return resp.read()


def specifiers(text):
    return [m.group(3) for m in SPEC.finditer(text)]


def static_deps(text, path):
    """Relative static imports of `path`, as served paths."""
    out = []
    for m in SPEC.finditer(text):
        if "(" in m.group(1) or not m.group(3).startswith("."):
            continue
        out.append(posixpath.normpath(
            posixpath.join(posixpath.dirname(path), m.group(3))))
    return out


def eager_closure(files, entry):
    """Served paths that the browser loads before `entry` runs."""
    seen, queue = [], [entry]
    while queue:
        path = queue.pop(0)
        if path in seen:
            continue
        seen.append(path)
        queue += static_deps(files[path][0].decode("utf-8"), path)
    return sorted(seen)


def write_rust(files, eager):
    lines = [
        "// @generated by scripts/vendor.py. Do not edit.",
        "",
        "/// Served paths of the vendored files, sorted.",
        "#[cfg(test)]",
        "pub(crate) const VENDORED: &[&str] = &[",
    ]
    lines += [f'    "{VENDOR}/{p}",' for p in sorted(files)]
    lines += [
        "];",
        "",
        "/// Vendored modules that load before the markstream entry runs.",
        "pub(crate) const EAGER_MODULES: &[&str] = &[",
    ]
    lines += [f'    "{VENDOR}/{p}",' for p in eager]
    lines += [
        "];",
        "",
        "/// Expands to the bundle file list: the extra entries, then each",
        "/// vendored file.",
        "macro_rules! vendored_files {",
        "    ($($extra:expr),* $(,)?) => {",
        "        &[",
        "            $($extra,)*",
    ]
    lines += [
        f'            ("{VENDOR}/{p}", include_bytes!('
        f'"../assets/{VENDOR}/{p}")),'
        for p in sorted(files)
    ]
    lines += ["        ]", "    };", "}", "pub(crate) use vendored_files;", ""]
    with open(os.path.join(ROOT, "src", "vendored.rs"), "w") as f:
        f.write("\n".join(lines))


def rewrite(text, served_path, targets):
    """Replace each bare specifier in `targets` with a relative path."""
    here = posixpath.dirname(served_path)

    def sub(m):
        spec = m.group(3)
        if spec not in targets:
            return m.group(0)
        rel = posixpath.relpath(targets[spec], here)
        if not rel.startswith("."):
            rel = "./" + rel
        return f"{m.group(1)}{m.group(2)}{rel}{m.group(2)}"

    return SPEC.sub(sub, text)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--from", dest="local",
                        help="read <DIR>/<pkg>/<version>/<path>, not the CDN")
    args = parser.parse_args()

    targets = {name: s[3] for name, s in SINGLES.items()}
    files = {}  # served path -> (bytes, source dict)

    def add(served, upstream_bytes, out_bytes, pkg, version, path):
        files[served] = (out_bytes, {
            "package": pkg,
            "version": version,
            "source": f"{CDN}/{pkg}@{version}/{path}",
            "upstream_integrity": sri(upstream_bytes),
            "integrity": sri(out_bytes),
            "rewritten": upstream_bytes != out_bytes,
        })

    for pkg, version, path, served in SINGLES.values():
        raw = fetch(pkg, version, path, args.local)
        out = rewrite(raw.decode("utf-8"), served, targets).encode("utf-8")
        add(served, raw, out, pkg, version, path)

    pkg, version = MARKSTREAM
    queue = ["dist/index.js"]
    seen = set()
    while queue:
        path = queue.pop()
        if path in seen:
            continue
        seen.add(path)
        raw = fetch(pkg, version, path, args.local)
        text = raw.decode("utf-8")
        for spec in specifiers(text):
            if spec.startswith("."):
                dep = posixpath.normpath(
                    posixpath.join(posixpath.dirname(path), spec))
                queue.append(dep)
            elif spec not in targets and spec not in OPTIONAL_PEERS:
                sys.exit(f"unknown bare import {spec!r} in {path}")
        served = posixpath.join(MARKSTREAM_DIR, path[len("dist/"):])
        out = rewrite(text, served, targets).encode("utf-8")
        add(served, raw, out, pkg, version, path)

    css_path, css_served = MARKSTREAM_CSS
    css = fetch(pkg, version, css_path, args.local)
    add(css_served, css, css, pkg, version, css_path)

    for served, (data, _) in files.items():
        dest = os.path.join(ASSETS, VENDOR, served)
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        with open(dest, "wb") as f:
            f.write(data)

    manifest = {
        "homepage": "https://markstream.simonhe.me",
        "license": "MIT (see assets/licenses/)",
        "notes": ("Vendoring provenance. Not served. 'upstream_integrity' "
                  "pins the bytes from the CDN. 'integrity' pins the served "
                  "bytes after the bare-import rewrite."),
        "optional_peers": sorted(OPTIONAL_PEERS),
        "files": {f"{VENDOR}/{k}": v for k, (_, v) in sorted(files.items())},
    }
    with open(os.path.join(ASSETS, "manifest.json"), "w") as f:
        json.dump(manifest, f, indent=2, sort_keys=True)
        f.write("\n")
    eager = eager_closure(files, f"{MARKSTREAM_DIR}/index.js")
    write_rust(files, eager)
    print(f"vendored {len(files)} files, {len(eager)} eager modules")


if __name__ == "__main__":
    main()
