// @generated by scripts/vendor.py. Do not edit.

/// Served paths of the vendored files, sorted.
#[cfg(test)]
pub(crate) const VENDORED: &[&str] = &[
    "vendor/floating-ui/core.js",
    "vendor/floating-ui/dom.js",
    "vendor/markstream-core/index.js",
    "vendor/markstream-vue/CodeBlockNode.js",
    "vendor/markstream-vue/PreCodeBlock.js",
    "vendor/markstream-vue/PreCodeBlock.vue_vue_type_style_index_0_lang.js",
    "vendor/markstream-vue/Tooltip.js",
    "vendor/markstream-vue/diagramHeight.js",
    "vendor/markstream-vue/exports.js",
    "vendor/markstream-vue/extended.js",
    "vendor/markstream-vue/index.css",
    "vendor/markstream-vue/index.js",
    "vendor/markstream-vue/index10.js",
    "vendor/markstream-vue/index2.js",
    "vendor/markstream-vue/index3.js",
    "vendor/markstream-vue/index4.js",
    "vendor/markstream-vue/index5.js",
    "vendor/markstream-vue/index6.js",
    "vendor/markstream-vue/index7.js",
    "vendor/markstream-vue/index8.js",
    "vendor/markstream-vue/index9.js",
    "vendor/markstream-vue/layout.js",
    "vendor/markstream-vue/mermaidSequenceSemicolons.js",
    "vendor/markstream-vue/preCodeDiffMetrics.js",
    "vendor/markstream-vue/streamDiffs.js",
    "vendor/markstream-vue/utils/katex-threshold.js",
    "vendor/markstream-vue/utils/performance-monitor.js",
    "vendor/markstream-vue/utils/safeRaf.js",
    "vendor/markstream-vue/workers-katexWorkerClient.js",
    "vendor/markstream-vue/workers-mermaidWorkerClient.js",
    "vendor/markstream-vue/workers/katexCdnWorker.js",
    "vendor/markstream-vue/workers/mermaidCdnWorker.js",
    "vendor/stream-markdown-parser/index.js",
    "vendor/vue/vue.runtime.esm-browser.prod.js",
];

/// Vendored modules that load before the markstream entry runs.
pub(crate) const EAGER_MODULES: &[&str] = &[
    "vendor/markstream-core/index.js",
    "vendor/markstream-vue/diagramHeight.js",
    "vendor/markstream-vue/exports.js",
    "vendor/markstream-vue/index.js",
    "vendor/markstream-vue/index2.js",
    "vendor/markstream-vue/utils/katex-threshold.js",
    "vendor/markstream-vue/utils/performance-monitor.js",
    "vendor/markstream-vue/utils/safeRaf.js",
    "vendor/markstream-vue/workers-katexWorkerClient.js",
    "vendor/markstream-vue/workers-mermaidWorkerClient.js",
    "vendor/markstream-vue/workers/katexCdnWorker.js",
    "vendor/markstream-vue/workers/mermaidCdnWorker.js",
    "vendor/stream-markdown-parser/index.js",
    "vendor/vue/vue.runtime.esm-browser.prod.js",
];

/// Expands to the bundle file list: the extra entries, then each
/// vendored file.
macro_rules! vendored_files {
    ($($extra:expr),* $(,)?) => {
        &[
            $($extra,)*
            ("vendor/floating-ui/core.js", include_bytes!("../assets/vendor/floating-ui/core.js")),
            ("vendor/floating-ui/dom.js", include_bytes!("../assets/vendor/floating-ui/dom.js")),
            ("vendor/markstream-core/index.js", include_bytes!("../assets/vendor/markstream-core/index.js")),
            ("vendor/markstream-vue/CodeBlockNode.js", include_bytes!("../assets/vendor/markstream-vue/CodeBlockNode.js")),
            ("vendor/markstream-vue/PreCodeBlock.js", include_bytes!("../assets/vendor/markstream-vue/PreCodeBlock.js")),
            ("vendor/markstream-vue/PreCodeBlock.vue_vue_type_style_index_0_lang.js", include_bytes!("../assets/vendor/markstream-vue/PreCodeBlock.vue_vue_type_style_index_0_lang.js")),
            ("vendor/markstream-vue/Tooltip.js", include_bytes!("../assets/vendor/markstream-vue/Tooltip.js")),
            ("vendor/markstream-vue/diagramHeight.js", include_bytes!("../assets/vendor/markstream-vue/diagramHeight.js")),
            ("vendor/markstream-vue/exports.js", include_bytes!("../assets/vendor/markstream-vue/exports.js")),
            ("vendor/markstream-vue/extended.js", include_bytes!("../assets/vendor/markstream-vue/extended.js")),
            ("vendor/markstream-vue/index.css", include_bytes!("../assets/vendor/markstream-vue/index.css")),
            ("vendor/markstream-vue/index.js", include_bytes!("../assets/vendor/markstream-vue/index.js")),
            ("vendor/markstream-vue/index10.js", include_bytes!("../assets/vendor/markstream-vue/index10.js")),
            ("vendor/markstream-vue/index2.js", include_bytes!("../assets/vendor/markstream-vue/index2.js")),
            ("vendor/markstream-vue/index3.js", include_bytes!("../assets/vendor/markstream-vue/index3.js")),
            ("vendor/markstream-vue/index4.js", include_bytes!("../assets/vendor/markstream-vue/index4.js")),
            ("vendor/markstream-vue/index5.js", include_bytes!("../assets/vendor/markstream-vue/index5.js")),
            ("vendor/markstream-vue/index6.js", include_bytes!("../assets/vendor/markstream-vue/index6.js")),
            ("vendor/markstream-vue/index7.js", include_bytes!("../assets/vendor/markstream-vue/index7.js")),
            ("vendor/markstream-vue/index8.js", include_bytes!("../assets/vendor/markstream-vue/index8.js")),
            ("vendor/markstream-vue/index9.js", include_bytes!("../assets/vendor/markstream-vue/index9.js")),
            ("vendor/markstream-vue/layout.js", include_bytes!("../assets/vendor/markstream-vue/layout.js")),
            ("vendor/markstream-vue/mermaidSequenceSemicolons.js", include_bytes!("../assets/vendor/markstream-vue/mermaidSequenceSemicolons.js")),
            ("vendor/markstream-vue/preCodeDiffMetrics.js", include_bytes!("../assets/vendor/markstream-vue/preCodeDiffMetrics.js")),
            ("vendor/markstream-vue/streamDiffs.js", include_bytes!("../assets/vendor/markstream-vue/streamDiffs.js")),
            ("vendor/markstream-vue/utils/katex-threshold.js", include_bytes!("../assets/vendor/markstream-vue/utils/katex-threshold.js")),
            ("vendor/markstream-vue/utils/performance-monitor.js", include_bytes!("../assets/vendor/markstream-vue/utils/performance-monitor.js")),
            ("vendor/markstream-vue/utils/safeRaf.js", include_bytes!("../assets/vendor/markstream-vue/utils/safeRaf.js")),
            ("vendor/markstream-vue/workers-katexWorkerClient.js", include_bytes!("../assets/vendor/markstream-vue/workers-katexWorkerClient.js")),
            ("vendor/markstream-vue/workers-mermaidWorkerClient.js", include_bytes!("../assets/vendor/markstream-vue/workers-mermaidWorkerClient.js")),
            ("vendor/markstream-vue/workers/katexCdnWorker.js", include_bytes!("../assets/vendor/markstream-vue/workers/katexCdnWorker.js")),
            ("vendor/markstream-vue/workers/mermaidCdnWorker.js", include_bytes!("../assets/vendor/markstream-vue/workers/mermaidCdnWorker.js")),
            ("vendor/stream-markdown-parser/index.js", include_bytes!("../assets/vendor/stream-markdown-parser/index.js")),
            ("vendor/vue/vue.runtime.esm-browser.prod.js", include_bytes!("../assets/vendor/vue/vue.runtime.esm-browser.prod.js")),
        ]
    };
}
pub(crate) use vendored_files;
